### ISSUE TITLE
Application crashes.

### ISSUE THREAD

**Issue by muhammadabdullah007git** [giantpinkrobots/varia#135]
Application crashesh after install.

OS : Arch

Error : 
Probably not a Flatpak environment. Trying to find the system's aria2c and yt-dlp...
Traceback (most recent call last):
  File "/usr/local/share/varia/../../bin/varia-py.py", line 37, in <module>
    sys.exit(main(VERSION, aria2cexec, ytdlpexec))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/varia/varia/variamain.py", line 398, in main
    if (os.path.exists(GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_DOWNLOAD))):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by N0tACyb0rg** [comment]
What version are you on? This was fixed in #108 and released in v2024.11.7.

**Comment by giantpinkrobots** [comment]
The part where it says "Probably not a Flatpak environment. Trying to find the system's aria2c **_and yt-dlp_**..." shows you have the next branch installed. It's not supposed to be on the AUR. Are you sure you have it installed through the AUR? The next branch is not guaranteed to be built outside Flatpak.

**Comment by shasherazi** [comment]
I'm facing a similar error

```
Traceback (most recent call last):
  File "/usr/share/varia/../../bin/varia-py.py", line 52, in <module>
    sys.exit(main(VERSION, aria2cexec, ffmpegexec, issnap))
             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/varia/varia/variamain.py", line 615, in main
    if (os.path.exists(GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_DOWNLOAD))):
        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

`varia 2025.5.14-1` AUR version
