### ISSUE TITLE
ModuleNotFoundError: No module named 'aria2p'

### ISSUE THREAD

**Issue by denisgolius** [giantpinkrobots/varia#16]
After installation via meson I failed in issue with installed varia package.

```bash
sudo varia
/usr/local/bin/varia: line 5: /usr/local/share/varia/../../aria2/aria2c: No such file or directory
Traceback (most recent call last):
  File "/usr/local/share/varia/../../bin/varia-py.py", line 38, in <module>
    from variamain import main
  File "/usr/local/share/varia/varia/variamain.py", line 12, in <module>
    import aria2p
ModuleNotFoundError: No module named 'aria2p'
```

I've installed aria2p, but I got a new error:
```fish
/usr/local/bin/varia: line 5: /usr/local/share/varia/../../aria2/aria2c: No such file or directory

(varia-py.py:560721): Gtk-WARNING **: 14:43:51.493: Unable to acquire session bus: Error spawning command line “dbus-launch --autolaunch=83757cafc35949a19a8eaad029cd91ef --binary-syntax --close-stderr”: Child process exited with code 1
Traceback (most recent call last):
  File "/usr/local/share/varia/varia/variamain.py", line 567, in on_activate
    self.win = MainWindow(application=app)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/varia/varia/variamain.py", line 144, in __init__
    with open(os.path.join(self.appdir, 'varia.conf'), 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/data/varia.conf'
^C⏎ 
```

Any suggestions?

PS: here is my PC specs
```
Linux garuda 6.6.2-AMD-znver3 #1 SMP PREEMPT_DYNAMIC Tue Nov 21 07:22:36 CET 2023 x86_64 GNU/Linux
Python 3.11.6
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
fish, version 3.6.1
```

**Comment by giantpinkrobots** [comment]
It's my bad, I forgot about a lot of the things I needed to do before adding non-Flatpak build instructions. For now, if you can install it with Flatpak please do that, otherwise you have to wait until I fix the issues.

**Comment by giantpinkrobots** [comment]
The new building from source guide is here. Thanks for waiting for so long. The new guide should work just fine.
