### ISSUE TITLE
Application "hangs,freezes" after 10+ Downloads, but continues to download

### ISSUE THREAD

**Issue by superuser-miguel** [giantpinkrobots/varia#34]
The application is Hanging, freezing after 10+ downloads, I can't seem to get meaningful logs or any logging from the application.

  4:04:15 PM systemd: app-flatpak-io.github.giantpinkrobots.varia-98084.scope: Consumed 2min 50.437s CPU time.
 4:04:15 PM python3: aria2p.client.ClientException: GID 850ef240be1757ad is not found
 4:04:15 PM python3: aria2p.client.ClientException: GID 850ef240be1757ad is not found
 4:04:15 PM python3:     raise Client.response_as_exception(response)
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 392, in res_or_raise
 4:04:15 PM python3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:04:15 PM python3:     return self.res_or_raise(self.post(payload))
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 265, in call
 4:04:15 PM python3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:04:15 PM python3:     return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 1460, in remove_download_result
 4:04:15 PM python3:     self.client.remove_download_result(download.gid)
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/api.py", line 462, in remove
 4:04:15 PM python3:     ^^^^^^^^^^^^
 4:04:15 PM python3:     raise result  # type: ignore  # we know it's a ClientException
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/downloads.py", line 1028, in remove
 4:04:15 PM python3:     self.download.remove(force=True)
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 739, in stop
 4:04:15 PM python3:     self.stop(False)
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 722, in pause
 4:04:15 PM python3:     download_thread.pause()
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 359, in pause_all
 4:04:15 PM python3:     self.pause_all("no","no")
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 633, in exitProgram
 4:04:15 PM python3:     app.win.exitProgram(app)
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 785, in main
 4:04:15 PM python3:              ^^^^^^^^^^^^^
 4:04:15 PM python3:     sys.exit(main(VERSION))
 4:04:15 PM python3:   File "/app/bin/varia-py.py", line 39, in <module>
 4:04:15 PM python3: Traceback (most recent call last):
 4:04:15 PM python3: During handling of the above exception, another exception occurred:
 4:04:15 PM python3: aria2p.client.ClientException: GID 850ef240be1757ad is not found
 4:04:15 PM python3:     raise Client.response_as_exception(response)
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 392, in res_or_raise
 4:04:15 PM python3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:04:15 PM python3:     return self.res_or_raise(self.post(payload))
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 265, in call
 4:04:15 PM python3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:04:15 PM python3:     return self.call(self.FORCE_PAUSE, [gid])  # type: ignore
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 709, in force_pause
 4:04:15 PM python3:     pause_func(download.gid)
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/api.py", line 541, in pause
 4:04:15 PM python3:     ^^^^^^^^^^^^
 4:04:15 PM python3:     raise result  # type: ignore  # we know it's a ClientException
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/downloads.py", line 1046, in pause
 4:04:15 PM python3:     self.download.pause([self.download.gid])
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 719, in pause
 4:04:15 PM python3: Traceback (most recent call last):
 4:04:15 PM python3: During handling of the above exception, another exception occurred:
 4:04:15 PM python3: aria2p.client.ClientException: GID 850ef240be1757ad is not found
 4:04:15 PM python3:     raise Client.response_as_exception(response)
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 392, in res_or_raise
 4:04:15 PM python3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:04:15 PM python3:     return self.res_or_raise(self.post(payload))
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 265, in call
 4:04:15 PM python3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:04:15 PM python3:     return self.call(self.PAUSE, [gid])  # type: ignore
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/client.py", line 673, in pause
 4:04:15 PM python3:     pause_func(download.gid)
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/api.py", line 541, in pause
 4:04:15 PM python3:     ^^^^^^^^^^^^
 4:04:15 PM python3:     raise result  # type: ignore  # we know it's a ClientException
 4:04:15 PM python3:   File "/app/lib/python3.11/site-packages/aria2p/downloads.py", line 1046, in pause
 4:04:15 PM python3:     self.download.pause()
 4:04:15 PM python3:   File "/app/share/varia/varia/variamain.py", line 715, in pause
 4:04:15 PM python3: Traceback (most recent call last):
 4:04:15 PM python3:
**REDACTED**
 4:04:15 PM python3: Download added.
 4:04:15 PM python3: 
 4:04:15 PM gnome-shell: clutter_actor_get_preferred_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
 4:04:15 PM gnome-shell: clutter_actor_get_preferred_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
 4:04:15 PM gnome-shell: clutter_actor_get_preferred_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
 4:03:30 PM systemd: Started tracker-extract-3.service - Tracker metadata extractor.
 4:03:30 PM flameshot: flameshot: info: Capture saved as /home/<USER>/Pictures/Screenshots/2024-01-03_16-03-28.png
 4:03:21 PM gnome-shell: Window manager warning: WM_TRANSIENT_FOR window 0x1000006 for override-redirect window 0x1000027 is an override-redirect window and this is not correct according to the standard, so we'll fallback to the root window.
 4:03:07 PM aria2c: 01/03 16:03:07 [[1;32mNOTICE[0m] Download complete: /home/<USER>/Downloads/
 4:03:06 PM gnome-shell: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1000008 specified for 0x1000006.
 4:03:06 PM xdg-desktop-por: Failed to associate portal window with parent window ''

![2024-01-03_16-03-28](https://github.com/giantpinkrobots/varia/assets/16271056/de89a243-f6f0-4023-93e8-f6328bdd98bb)

**Comment by giantpinkrobots** [comment]
Hello. To test this I have added like thirty ubuntu downloads by spamming the Download button, and the app still works fine for me. It seems like the app tries to interact with downloads that do not exist within aria2. Does this issue happen regularly? Like, after doing something within the app, or after closing and reopening it?

**Comment by superuser-miguel** [comment]
Hey there, I will have to retest this scenario for you since it has been some days since this happened. Today I will be downloading a bunch so i will retest.

**Comment by giantpinkrobots** [comment]
Hello, did the issue persist? Or did it work fine with the new update?

**Comment by superuser-miguel** [comment]
Hi, it's been some time since i opened this issue. I've been using Varia a lot over the last 4 days and the issue is worse now.

I typically leave Varia open in a workspace and go off and do other things, Varia Freezes, Hangs after a period of time. So to test, I watched it for about 15-30 mins, the application hangs and will resume after I shrink the application. 

I don't have any logs right now, but will attempt again by starting it from the terminal. 

I am not aware of debugging tools in the Flatpak runtime, but I do know how to navigate the flatpak environment and possibly install a debugger if you need me to? 

I'd really like to get that solved as I will be using Varia heavily for at least the next 2 months to recover some files I lost.

**Comment by superuser-miguel** [comment]
Here is my current hardware config:

```
System:
  Host: n/a Kernel: 6.9.12-200.fc40.x86_64 arch: x86_64 bits: 64
    compiler: gcc v: 2.41-37.fc40
  Desktop: GNOME v: 46.3.1 tk: GTK v: 3.24.43 wm: gnome-shell dm: GDM
    Distro: Fedora Linux 40 (Workstation Edition)
Machine:
  Type: Laptop System: LENOVO product: 82K2 v: IdeaPad Gaming 3 15ACH6
    serial: <superuser required> Chassis: type: 10 v: IdeaPad Gaming 3 15ACH6
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0T76465 WIN
    serial: <superuser required> part-nu: LENOVO_MT_82K2_BU_idea_FM_IdeaPad
    Gaming 3 15ACH6 UEFI: LENOVO v: H3CN32WW(V2.02) date: 02/23/2022
Battery:
  ID-1: BAT1 charge: 32.1 Wh (81.1%) condition: 39.6/45.0 Wh (87.9%)
    volts: 12.9 min: 11.5 model: 0x43 0x65 0x6C 0x78 0x70 0x72 0x74 0x00 0x32
    0x30 0x4C 0x32 0x30 0x43 0x33 0x50 serial: 4500 status: charging
CPU:
  Info: 6-core model: AMD Ryzen 5 5600H with Radeon Graphics bits: 64
    type: MT MCP arch: Zen 3 rev: 0 cache: L1: 384 KiB L2: 3 MiB L3: 16 MiB
  Speed (MHz): avg: 3865 high: 3868 min/max: 400/4280 cores: 1: 3868 2: 3849
    3: 3865 4: 3868 5: 3868 6: 3868 7: 3868 8: 3868 9: 3863 10: 3868 11: 3863
    12: 3868 bogomips: 79056
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GA107M [GeForce RTX 3050 Ti Mobile] vendor: Lenovo
    driver: nvidia v: 560.31.02 arch: Ampere pcie: speed: 8 GT/s lanes: 8
    bus-ID: 01:00.0 chip-ID: 10de:25a0
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    vendor: Lenovo driver: amdgpu v: kernel arch: GCN-5 pcie: speed: 8 GT/s
    lanes: 16 ports: active: eDP-1 empty: HDMI-A-1 bus-ID: 05:00.0
    chip-ID: 1002:1638 temp: 54.0 C
  Device-3: IMC Networks Integrated Camera driver: uvcvideo type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 bus-ID: 1-3:2 chip-ID: 13d3:56ff
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 24.1.1
    compositor: gnome-shell driver: X: loaded: amdgpu,nvidia
    unloaded: fbdev,modesetting,nouveau,vesa alternate: nv dri: radeonsi
    gpu: amdgpu display-ID: 0
  Monitor-1: eDP-1 model: BOE Display 0x0a81 res: 1920x1080 dpi: 142
    diag: 395mm (15.5")
  API: OpenGL v: 4.6 vendor: amd mesa v: 24.1.5 glx-v: 1.4 es-v: 3.2
    direct-render: yes renderer: AMD Radeon Graphics (radeonsi renoir LLVM
    18.1.6 DRM 3.57 6.9.12-200.fc40.x86_64) device-ID: 1002:1638
    display-ID: :0.0
  API: Vulkan v: 1.3.283 surfaces: xcb,xlib,wayland device: 0
    type: integrated-gpu driver: N/A device-ID: 1002:1638 device: 1
    type: discrete-gpu driver: N/A device-ID: 10de:25a0 device: 2 type: cpu
    driver: N/A device-ID: 10005:0000
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio vendor: Lenovo
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 16
    bus-ID: 05:00.1 chip-ID: 1002:1637
  Device-2: AMD ACP/ACP3X/ACP6x Audio Coprocessor vendor: Lenovo driver: N/A
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 05:00.5 chip-ID: 1022:15e2
  Device-3: AMD Family 17h/19h HD Audio vendor: Lenovo driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 05:00.6 chip-ID: 1022:15e3
  API: ALSA v: k6.9.12-200.fc40.x86_64 status: kernel-api
  Server-1: PipeWire v: 1.0.7 status: active with: 1: pipewire-pulse
    status: active 2: wireplumber status: active 3: pipewire-alsa type: plugin
    4: pw-jack type: plugin

```

**Comment by superuser-miguel** [comment]
From further testing, it's as if the application is not "should I say" refreshing it's current state. Appearing to hang when in fact, it is working. So it looks like it's freezing, hanging when in fact it's not reporting it's current state. Also this happens: 

![2024-08-15_10-03-37](https://github.com/user-attachments/assets/ef4ea973-9f78-4d8b-83af-16922f8594bf)

**Comment by superuser-miguel** [comment]
Hi there, It's been so long and so many updates to this application. I'm only adding this as I was told by someone I recommended the app to that they still experienced these issues. I'll need to re-download and test again but this appears to still be an issue.

**Comment by ximGBu4cyQss5P** [comment]
Seeing the same behavior with Fedora 41 / KDE Plasma 6.3.3 / kernel 6.13.7 / Firefox 136.0.2 / Varia integrator extension 1.2 (both Varia and FireFox are flatpaks) .  The UI eventually freezes but the downloads continue in the background.  The UI stays frozen even after all downloads complete.  If I right click the program icon in the panel and pick the close action, I'll eventually get an option to kill the unresponsive app.  If I do that, Varia keeps running in the background (which is good), and subsequent downloads will fire up the GUI again which works for a while but eventually freezes again.
