### ISSUE TITLE
AttributeError: 'MyApp' object has no attribute 'win'

### ISSUE THREAD

**Issue by denisgolius** [giantpinkrobots/varia#43]
So after [building](https://github.com/giantpinkrobots/varia#building)  varia I've got another issue when I tried to run it:

```shell
which varia
/usr/local/bin/varia
```

```shell
varia
Probably not a Flatpak environment. Trying to find the system's aria2c...
/usr/local/bin/varia: line 15: --enable-rpc: command not found
Traceback (most recent call last):
  File "/usr/local/share/varia/../../bin/varia-py.py", line 39, in <module>
    sys.exit(main(VERSION))
  File "/usr/local/share/varia/varia/variamain.py", line 988, in main
    app.win.exitProgram(app)
AttributeError: 'MyApp' object has no attribute 'win'
```

**Comment by giantpinkrobots** [comment]
Were you able to run it afterwards? If so I will be closing this.

**Comment by denisgolius** [comment]
> Were you able to run it afterwards? If so I will be closing this.

Hey, sorry, I will answer in a few hours.

**Comment by giantpinkrobots** [comment]
I am assuming this is fixed now. Please reopen if the issue has persisted.
